[package]
name = "symbiants_pkg"
version = "0.1.0"
edition = "2021"

[lib]
name = "symbiants_lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.11.3", default-features = false, features = [
  "bevy_asset",
  "bevy_scene",
  "bevy_winit",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_sprite",
  "bevy_text",
  "default_font",
  "png",
] }
bevy_egui = { version = "0.22.0" }
bevy_save = { version = "0.9.1" }
bevy_turborand = { version = "0.6.0" }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
sun-times = { version = "0.2.0" }
uuid = { version = "1.4.1" }

# WASM builds require extra dependencies for logging and persisting state to local storage.
# WASM builds do not require x11 and cannot use dynamic_linking.
[target.'cfg(target_family = "wasm")'.dependencies]
brotli = { version = "3.4.0" }
console_error_panic_hook = { version = "0.1.7" }
gloo-storage = "0.3.0"
js-sys = { version = "0.3.64", default-features = false }
rmp-serde = { version = "1.1.2" }
wasm-bindgen = { version = "0.2.87" }
web-sys = { version = "0.3.64", features = [
  "EventTarget",
  "Window",
  "BeforeUnloadEvent",
] }

# Linux builds require x11. dynamic_linking isn't required, but improves repeated compilation performance.
# dynamic_linking should not be included in release builds. It's fine to hardcode it here because only WASM is released.
[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy = { version = "0.11.3", default-features = false, features = [
  "x11",
  "dynamic_linking",
] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
