[package]
name = "antfarmpkg"
version = "0.1.0"
edition = "2021"

[lib]
name = "antfarm"
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = { version = "0.11.0" }
bevy_save = { path = "../bevy_save/" }
console_error_panic_hook = { version = "0.1.7" }
wasm-bindgen = { version = "0.2.87" }
uuid = { version = "1.4.0" }
rand = { version = "0.8.5" }
itertools = "0.11.0"
gloo-storage = "0.3.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = { version = "1.0.104" }
js-sys = { version = "0.3.64", default-features = false }
web-sys = { version = "0.3.64", features = [
  "EventTarget",
  "Window",
  "BeforeUnloadEvent",
] }
chrono = { version = "0.4.26", features = ["serde"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
