[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: remove non-simulation features (sprite, text, etc.)
bevy = { version = "0.12.1", default-features = false, features = [
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
] }
serde = { version = "1.0.188", features = ["derive"] }
bevy_turborand = { version = "0.7.0" }
bevy_save = { version = "0.13.0" }
chrono = { version = "0.4.31", features = ["serde"] }
sun-times = { version = "0.2.0" }

# WASM builds require extra dependencies for logging and persisting state to local storage.
# WASM builds do not require x11 and cannot use dynamic_linking.
[target.'cfg(target_family = "wasm")'.dependencies]
brotli = { version = "3.4.0" }
gloo-storage = "0.3.0"
js-sys = { version = "0.3.64", default-features = false }
rmp-serde = { version = "1.1.2" }
wasm-bindgen = { version = "0.2.87" }
web-sys = { version = "0.3.64", features = [
    "EventTarget",
    "Window",
    "BeforeUnloadEvent",
] }
