[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # Prefer using mold over lld - 5x quicker.
    "-C", "link-arg=--ld-path=/usr/bin/mold",
    "-Z", "share-generics=y"
]